config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/prepare',   to: 'static_pages#prepare'
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/health_records',  to: 'health_records#new'
  get '/meal_records', to: 'meal_records#new'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers, :students, :header_records, :meal_records
    end
  end
  resources :microposts, only: [:show, :create, :destroy] do
    resources :reposts, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :deep_relationships, only: [:create, :destroy]
  resources :health_records, only: [:create, :destroy]
  resources :meal_records, only: [:edit, :create, :destroy]
  resources :replies, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  has_many :replies_to_reply, class_name: "Reply", foreign_key: :reply_id, dependent: :destroy
  has_many :notifications, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :micropost_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    if params[:reply_id]
      @reply = Reply.find(params[:reply_id]).replies_to_reply.build(reply_params)
      @reply.user_id = current_user.id
      @reply.micropost_id = params[:micropost_id]
    else
      @reply = current_user.replies.build(reply_params)
      @reply.micropost_id = params[:micropost_id]
    end

    if @reply.save
      flash[:success] = "投稿しました！"
      @reply.post.create_reply_notification!(current_user, @reply.id)
      redirect_to request.referer
    else
      flash[:success] = "投稿に失敗しました！"
      redirect_to request.referer
    end
  end

  def destroy

  end

  private

  def reply_params
    params.require(:reply).permit(:content)
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_reply.html.erb
<li class="" id="reply-<%= reply.id %>">
  <article class="reply_article">
    <a href="<%= reply_path(reply.id) %>">
      <header>
        <div class="reply_profile_img">
          <object>
            <a href="<%= user_path(reply.user) %>"><%= image_tag reply.user.image_name.url %></a>
          </object>
        </div>
        <div class="reply_user_name">
          <object>
            <a href="<%= user_path(reply.user) %>"><%= reply.user.name %></a>
          </object>
        </div>
        <div class="reply_timestamp">
          <span><%= time_ago_in_words(reply.created_at) %>前</span>
        </div>
        <% if current_user.teacher == reply.user %>
        <div class="reply_relationship">
          <span>師匠</span>
          <img src="/images/teacher.svg" width="24" height="24" alt="">
        </div>
        <% elsif current_user.student?(reply.user) %>
        <div class="reply_relationship">
          <span>弟子<img src="/images/student.svg" width="24" height="24" alt=""></span>
        </div>
        <% end %>
      </header>
      <div class="reply_main">
        <div class="reply_content">
          <span><%= reply.content %></span>
        </div>
        <div class="reply_reaction">
          <div class="reply">
            <img src="/images/reply.svg" width="20" height="20" alt="">
          </div>
          <div class="remuscle">
            <img src="/images/remuscle.svg" width="20" height="20" alt="">
          </div>
          <div class="like">
            <img src="/images/like.svg" width="20" height="20" alt="">
            <div class="like_message">
              <span>キレてるね!</span>
            </div>
          </div>
        </div>
      </div>
    </a>
    <div class="reply_reply">
      <%= form_with model: reply.replies_to_reply, url: replies_path, local: true do |f| %>
        <%= hidden_field_tag :reply_id, reply.id %>
        <%= hidden_field_tag :micropost_id, @micropost.id %>
        <div class="reply_field">
          <%= f.text_area :content, id: "muscle_post_content", placeholder: "コメントする" %>
          <%= f.submit "送信", class: "btn reply_btn" %>
        </div>
      <% end %>
    </div>

  </article>
  <% if reply.replies_to_reply.any? %>
  <div class="micropost_replies_to_reply">
    <ol>
      <%= render partial: 'replies/reply_to_reply', collection: reply.replies_to_reply, as: 'reply' %>
    </ol>
  </div>
  <% end %>
</li>

app/views/replies/_reply_to_reply.html.erb
<li class="" id="reply-<%= reply.id %>">
  <article class="">
    <a href="<%= reply_path(reply.id) %>">
      <header>
        <div class="reply_profile_img">
          <object>
            <a href="<%= user_path(reply.user) %>"><%= image_tag reply.user.image_name.url %></a>
          </object>
        </div>
        <div class="reply_user_name">
          <object>
            <a href="<%= user_path(reply.user) %>"><%= reply.user.name %></a>
          </object>
        </div>
        <div class="reply_timestamp">
          <span><%= time_ago_in_words(reply.created_at) %>前</span>
        </div>
        <% if current_user.teacher == reply.user %>
        <div class="reply_relationship">
          <span>師匠</span>
          <img src="/images/teacher.svg" width="24" height="24" alt="">
        </div>
        <% elsif current_user.student?(reply.user) %>
        <div class="reply_relationship">
          <span>弟子<img src="/images/student.svg" width="24" height="24" alt=""></span>
        </div>
        <% end %>
      </header>
      <div class="reply_main">
        <div class="reply_content">
          <span><%= reply.content %></span>
        </div>
        <div class="reply_reaction">
          <div class="reply">
            <img src="/images/reply.svg" width="20" height="20" alt="">
          </div>
          <div class="remuscle">
            <img src="/images/remuscle.svg" width="20" height="20" alt="">
          </div>
          <div class="like">
            <img src="/images/like.svg" width="20" height="20" alt="">
            <div class="like_message">
              <span>キレてるね!</span>
            </div>
          </div>
        </div>
      </div>
    </a>
    <div class="reply_reply">
      <%= form_with model: reply.replies_to_reply, url: replies_path, local: true do |f| %>
        <%= hidden_field_tag :reply_id, reply.id %>
        <%= hidden_field_tag :micropost_id, @micropost.id %>
        <div class="reply_field">
          <%= f.text_area :content, id: "muscle_post_content", placeholder: "コメントする" %>
          <%= f.submit "送信", class: "btn reply_btn" %>
        </div>
      <% end %>
    </div>

  </article>
</li>

<% if reply.replies_to_reply.any? %>
<div class="micropost_replies_to_reply">
  <ol>
    <%= render partial: 'replies/reply_to_reply', collection: reply.replies_to_reply, as: 'reply' %>
  </ol>
</div>
<% end %>