config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/prepare',   to: 'static_pages#prepare'
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/health_records',  to: 'health_records#new'
  get '/meal_records', to: 'meal_records#new'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers, :students, :header_records, :meal_records
    end
  end
  resources :microposts, only: [:show, :create, :destroy] do
    resources :reposts, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :deep_relationships, only: [:create, :destroy]
  resources :health_records, only: [:create, :destroy]
  resources :meal_records, only: [:edit, :create, :destroy]
  resources :replies, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :microposts, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_one :active_deep_relationships, class_name:  "DeepRelationship",
                                   foreign_key: "student_id",
                                   dependent:   :destroy

  has_many :passive_deep_relationships, class_name: "DeepRelationship",
                                foreign_key: "teacher_id",
                                dependent:   :destroy
  has_one :teacher, through: :active_deep_relationships
  has_many :students, through: :passive_deep_relationships

  has_many :health_records, dependent: :destroy
  has_many :meal_records, dependent: :destroy
  has_many :reposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  mount_uploader :image_name, ImagenameUploader

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  validate  :image_name_size

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.trend_feed
    Micropost.limit(10)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # ユーザーのステータスフィードを返す
  def feed
    Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # ユーザーを弟子にする
  def student(other_user)
    students << other_user
  end

  # 現在のユーザーが弟子であればtrueを返す
  def student?(other_user)
    students.include?(other_user)
  end


  # ユーザーの弟子をやめる
  def not_teacher(other_user)
    active_deep_relationships.destroy
  end

  def convert_birthday_into_age
    if !birthday.nil?
    (Date.today.strftime("%Y%m%d").to_i - self.birthday.strftime("%Y%m%d").to_i) / 10000
    end
  end

  def reposted?(post_id)
    reposts.exists?(micropost_id: post_id)
  end

  def liked?(post_id)
    likes.exists?(micropost_id: post_id)
  end

  def create_follow_notification!(user)
    temp = Notification.where("visitor_id = ? and visited_id = ? and action = ? ",self.id, user.id, 'follow')
    if temp.blank?
      notification = active_notifications.new(
        visited_id: user.id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def create_like_notification!(post)
    # すでに「いいね」されているか検索
    temp = Notification.where("visitor_id = ? and visited_id = ? and micropost_id = ? and action = ? ", self.id, post.user_id, post.id, 'like')
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = active_notifications.new(
        micropost_id: post.id,
        visited_id: post.user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_reply_notification!(reply)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Reply.where('micropost_id = ? and user_id <> ?', reply.micropost_id, self.id).ids.uniq
    temp_ids.each do |temp_id|
      save_reply_notification!(reply, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_reply_notification!(reply, reply.micropost.user_id) if temp_ids.blank?
  end

  def save_reply_notification!(reply, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = active_notifications.new(
      micropost_id: reply.micropost_id,
      reply_id: reply.id,
      visited_id: visited_id,
      action: 'reply'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  private
  # アップロードされた画像のサイズをバリデーションする
  def image_name_size
    if image_name.size > 5.megabytes
      errors.add(:image_name, "should be less than 5MB")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_class, only:[:new, :create]
  before_action :logged_in_user, only: [:edit, :update,  :following, :followers, :teacher, :students]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.where.not(picture: nil)
    @col = 'col-md-4'
  end

  #get '/signup',  to: 'users#new'
  def new
    if logged_in?
      redirect_to (request.referer || root_url), status: 403
      flash[:danger] = "既にログインしています。"
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "#{@user.name}さん、ようこそMuscle Platformへ！"
      redirect_to root_url, status: 303
    else
      render 'new'
    end
  end

  def edit
    @male = @female = @default = false
    if @user.gender == 1
      @male = true
    elsif @user.gender == 2
      @female = true
    else
      @default = true
    end


  end

  def update
   if @user.update_attributes(user_params)
     flash[:success] = "更新に成功しました"
     redirect_to @user
   else
     flash.now[:danger] = "更新に失敗しました"
     render 'edit'
   end
 end

 def following
    @title = "フォロー"
    @user  = User.find(params[:id])
    @users = @user.following
    @follow_class = "active"
    render 'users/relationship'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers
    @follower_class = "active"
    render 'users/relationship'
  end

  def students
    @title = "弟子"
    @user  = User.find(params[:id])
    @users = @user.students
    @students_class = "active"
    render 'users/relationship'
   end

   def health_records
     h = current_user.health_records
     @health_records = h.take(current_user.health_records.count)
     @health_record = h.build(height: h.first&.height, weight: h.first&.weight, fat: h.first&.fat, measured_at: DateTime.now)

   end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :url, :bio, :tel, :image_name, :birthday, :gender)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def set_class
    @col = 'col-md-offset-4 col-md-4'
    @frame_design = ''
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def calc_growth(user, attr, perioud_units="month", perioud_number=1)
    if to_date = user.health_records.first&.measured_at

      case perioud_units
      when "day"
        from_date = to_date - perioud_number.day
      when "week"
        from_date = to_date - perioud_number.week
      when "month"
        from_date = to_date - perioud_number.month
      when "year"
        from_date = to_date - perioud_number.yaer
      end

      if from_record = user.health_records.find_by(measured_at: from_date.beginning_of_day...from_date.end_of_day)
        case attr
        when "height"
          from_attr = from_record.height
          to_attr = user.health_records.first.height
        when "weight"
          from_attr = from_record.weight
          to_attr = user.health_records.first.weight
        when "fat"
          from_attr = from_record.fat
          to_attr = user.health_records.first.fat
        when "muscle"
          from_attr = from_record.muscle
          to_attr = user.health_records.first.muscle
        end

        (to_attr - from_attr).round(1)
      else
        " ー "
      end
    else
      " ー "
    end
  end
end

app/views/users/_follow.html.erb
<%= form_with(model:user.passive_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "フォロー", class: "btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<div class="col-md-offset-1" id= <%= "follow_form_#{user.id}" %> >
<% if logged_in? && current_user.following?(user) %>
  <%= render 'unfollow', user: user %>
<% else %>
  <%= render 'follow', user: user %>
<% end %>
</div>

app/views/users/_not_student.html.erb
<%= form_with(model: user.active_deep_relationships, html: { method: :delete }, local:true) do |f| %>
  <%= f.submit "破門する", class: "btn btn-danger",
  data: { confirm: "この弟子を破門します。よろしいですか？"} %>
<% end %>

app/views/users/_not_teacher.html.erb
<%= form_with(model: user.passive_deep_relationships.find_by(student_id: current_user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "弟子をやめる", class: "btn btn-primary",
  data: { confirm: "弟子をやめます。よろしいですか？"} %>
<% end %>

app/views/users/_student_form.html.erb
<div id= <%= "student_form_#{user.id}" %> >
  <%= render 'not_student', user: user %>
</div>

app/views/users/_teacher.html.erb
<%= form_with(model:user.passive_deep_relationships.build) do |f| %>
  <div><%= hidden_field_tag :teacher_id, user.id %></div>
  <%= f.submit "弟子入り", class: "btn" %>
<% end %>

app/views/users/_teacher_form.html.erb
<div id= <%= "teacher_form_#{user.id}" %> >
<% if logged_in? && current_user.teacher == user %>
  <%= render 'not_teacher', user: user %>
<% else %>
  <%= render 'teacher', user: user %>
<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: user.passive_relationships.find_by(follower_id: current_user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-primary",
  data: { confirm: "フォローを解除します。よろしいですか？"} %>
<% end %>

app/views/users/_user.html.erb
<li class="relationship_user"　id=<%= "student_form_#{user.id}" %>>
  <div class="relationship_user_left">
    <a href="<%= user_path(user) %>">
      <%= image_tag user.image_name.url %>
    </a>
  </div>
  <div class="relationship_user_right">
    <div class="relationship_user_right_header">
      <div class="relationship_user_name">
        <a href="<%= user_path(user) %>">
          <span><%= user.name %></span>
        </a>
      </div>
      <% unless current_user?(user) %>
      <div class="relationship_make_btn">
        <div class="relationship_follow_btn">
          <%= render 'follow_form', { user: user} %>
        </div>
        <% unless user.teacher == current_user %>
        <div class="relationship_teacher_btn">
          <%= render 'teacher_form', { user: user} %>
        </div>
        <% else %>
        <div class="relationship_not_student_btn">
          <%= render 'student_form', { user: user} %>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <div class="relationship_user_right_content">
      <span><%= user.bio %></span>
    </div>

  </div>
</li>

app/views/users/edit.html.erb
<% provide(:title, "設定") %>

<div class="row">
  <ul class="nav nav-pills nav-stacked col-md-3 form_frame edit_nav">
    <li class="active"> <a href="#profile" class="edit_link" data-toggle="pill">プロフィールを編集</a> </li>
    <li> <a href="#password" class="edit_link" data-toggle="pill">パスワードを編集</a> </li>
  </ul>

    <div class="col-md-6 tab-content form_frame edit_main">
      <div class="tab-pane active" id="profile">
        <%= form_with model: @user, local: true,  multipart: true do |f| %>

          <h1>プロフィールを編集</h1>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :url %>
            <%= f.url_field :url, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :bio %>
            <%= f.text_area :bio, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :tel %>
            <%= f.telephone_field :tel, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :birthday %>
            <%= f.date_select :birthday, class: "form-control", use_month_numbers: true,
            start_year:Date.today.prev_year(100).year,
            end_year:Date.today.year, date_separator: '/' %>
          </div>

          <div class="form-group">
            <%= f.radio_button :gender, 1, checked: @male %>
            <%= f.label :gender, "男性", {value: :male, style: "display: inline-block;"} %>
            <%= f.radio_button :gender, 2 , checked: @female %>
            <%= f.label :gender, "女性", {value: :female, style: "display: inline-block;"} %>
            <%= f.radio_button :gender, 0, checked: @default %>
            <%= f.label :gender, "設定しない", {value: :default, style: "display: inline-block;"} %>
          </div>

          <div class="form-group">
            <%= f.label :image_name %>
            <%= f.file_field :image_name, accept: 'image/jpeg,image/gif,image/png' %>
          </div>


          <%= f.submit "更新する", disabled:true, class: "btn btn-primary signup_btn edit_profile_btn" %>

        <% end %>
      </div>

      <div class="tab-pane" id="password">
        <%= form_with model: @user, local: true do |f| %>

          <h1>パスワードを編集</h1>
          <div class="form-group">
            <%= f.label :password, "パスワード" %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, "パスワード(確認用)" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>

          <%= f.submit "更新する", disabled:true, class: "btn btn-primary signup_btn edit_password_btn" %>

        <% end %>
      </div>

    </div>
</div>

app/views/users/health_records.html.erb
<% provide(:title, current_user.name) %>
<div class="row health_records">
  <div class="col-md-4 health_records_form">
    <%= render 'health_records/new' %>
  </div>
  <div class="col-md-offset-1 col-md-7 health_records_table">
    <table>
      <tr>
      <% HealthRecord.column_names[1..7].each_with_index do |header, idx| %>
        <th><%= HealthRecord.human_attribute_name header %></th>
      <% end %>
      </tr>
      <%= render @health_records %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<%= render 'shared/signup', { col:@col, frame_design:@frame_design } %>

app/views/users/relationship.html.erb
<% provide(:title, @title) %>

<div class="relationship">
  <div class="relationship_sticky">
    <div class="relationship_profile">
      <div class="relationship_back_btn">
        <a href="<%= user_path @user %>">←</a>
      </div>
      <div class="relationship_profile_img">
        <%= image_tag @user.image_name.url %>
      </div>
      <div class="relationship_profile_name">
        <span><%= @user.name %></span>
      </div>
    </div>
    <ul class="nav nav-tabs relationship_nav">
      <li><a href="<%= following_user_path %>" class= <%= @follow_class %>>フォロー</a></li>
      <li><a href="<%= followers_user_path %>" class= <%= @follower_class %>>フォロワー</a></li>
      <li><a href="<%= students_user_path %>" class=<%= @students_class %>>弟子</a></li>
    </ul>
  </div>

  <div class="relationship_users_frame">
    <% if @users.any? %>
      <ul class="relationship_users">
        <%= render @users %>
      </ul>
    <% else %>
      <div class="relationship_nothing">
        <span><%= @user.name %>さんの<%= @title %>は0人です</span>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <section class="col-md-3 user_profile_left">
    <div class="profile_img">
      <%= image_tag @user.image_name.url %>
    </div>

    <div class="status">
      <span>称号 <span>バルクモンスター</span></span>
      <div>
        <div>
          <span>身長: <span><%= @user.health_records.first&.height || " ー " %></span>cm</span>
        </div>
        <div>
          <span>体重 <span><%= @user.health_records.first&.weight || " ー " %></span>kg</span>
          <span>前月比 <span><%= calc_growth(@user, "weight") %></span>kg</span>
        </div>
        <div>
          <span>体脂肪率 <span><%= @user.health_records.first&.fat || " ー " %></span>%</span>
          <span>前月比 <span><%= calc_growth(@user, "fat") %></span>%</span>
        </div>
        <div>
          <span>筋肉率 <span><%= @user.health_records.first&.muscle || " ー " %></span>%</span>
          <span>前月比 <span><%= calc_growth(@user, "muscle") %></span>%</span>
        </div>

      </div>
    </div>
  </section>

  <section class="user_profile_right col-md-9">
    <div class="row">
      <div class="col-md-4 user_profile_name">
        <h1><%= @user.name %></h1>
        <span><%= @user.convert_birthday_into_age %></span>
      </div>
      <% unless current_user?(@user) %>
        <%= render 'follow_form', { user: @user} %>
        <%= render 'teacher_form', { user: @user}  %>
      <% end %>
    </div>
    <div class="">
      <span class="signup_day"><%= @user.created_at.strftime('%Y/%m/%d') %>から、Muscle Platformを利用しています</span>
    </div>

    <ul class="row list-inline">
      <li><span>投稿 <span><%= @user.microposts.count %></span>件</span></li>
      <li><a href="<%= following_user_path(@user) %>">フォロー <span><%= @user.following.count %></span>人</a></li>
      <li><a href="<%= followers_user_path(@user) %>">フォロワー <span id="followers"><%= @user.followers.count %></span>人</a></li>
      <li><a href="<%= students_user_path(@user) %>">弟子 <span id="students"><%= @user.students.count %></span>人</a></li>
    </ul>

    <% if @user.teacher %>
    <div class="teacher">
      <span id="teacher_text"><a href="<%= user_path(@user.teacher) %>"><%= @user.teacher.name %></a>さんの弟子です</span>
    </div>
    <% end %>

    <div>
      <span><%= @user.bio %></span>
    </div>
  </section>
</div>

<div class="profile_garaly">
  <ul class="garaly_label">
    <li><a href="#"><span>全て</span></a></li>
    <li><a href="#"><span>筋肉</span></a></li>
    <li><a href="#"><span>食事</span></a></li>
  </ul>

  <article class="row">
      <ol class="microposts_garaly">
        <%= render @microposts %>
      </ol>
  </article>
</div>