config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/prepare',   to: 'static_pages#prepare'
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/health_records',  to: 'health_records#new'
  get '/meal_records', to: 'meal_records#new'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers, :students, :header_records, :meal_records
    end
  end
  resources :microposts, only: [:show, :create, :destroy] do
    resources :reposts, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :deep_relationships, only: [:create, :destroy]
  resources :health_records, only: [:create, :destroy]
  resources :meal_records, only: [:edit, :create, :destroy]
  resources :replies, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :replies, dependent: :destroy
  has_many :reposts, dependent: :destroy
  has_many :likes,   dependent: :destroy
  has_many :notifications, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, length: { maximum: 140 }
  validates :content_or_picture, presence: true
  validate  :picture_size

  private

  def content_or_picture
      content.presence or picture.presence
  end

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def show
    @micropost = Micropost.find_by(id: params[:id])
    @reply = Reply.new
    @replies = @micropost.replies.where(reply_id: nil)
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿しました！"
      redirect_to root_url
    else
      flash[:success] = "投稿に失敗しました！"
      redirect_to request.referer
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました！"
    redirect_to root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li class="" id="micropost-<%= micropost.id %>">
  <article class="">
    <a href="<%= micropost_path(micropost.id) %>">
      <% if @user.nil? %>
      <header>
        <div class="micropost_profile_img">
          <object>
            <a href="<%= user_path(micropost.user) %>"><%= image_tag micropost.user.image_name.url %></a>
          </object>
        </div>
        <div class="micropost_user_name">
          <object>
            <a href="<%= user_path(micropost.user) %>"><%= micropost.user.name %></a>
          </object>
        </div>
        <% if current_user.teacher == micropost.user %>
        <div class="micropost_relationship">
          <span>師匠</span>
          <img src="/images/teacher.svg" width="32" height="32" alt="">
        </div>
        <% elsif current_user.student?(micropost.user) %>
        <div class="micropost_relationship">
          <span>弟子<img src="/images/student.svg" width="32" height="32" alt=""></span>
        </div>
        <% end %>
      </header>
      <div class="micropost_main">
        <% if micropost.picture? %>
        <div class="micropost_main_img">
          <%= image_tag micropost.picture.url %>
        </div>
        <% end %>
        <% if micropost.content? %>
        <div class="micropost_content">
          <span><%= micropost.content %></span>
        </div>
        <% end %>
        <div class="micropost_reaction">
          <div class="reply">
            <img src="/images/reply.svg" width="24" height="24" alt="">
            <span><%= micropost.replies.count if micropost.replies.any? %></span>
          </div>
          <div class="remuscle">
            <img src="/images/remuscle.svg" width="24" height="24" alt="">
          </div>
          <div class="like">
            <img src="/images/like.svg" width="24" height="24" alt="">
            <div class="like_message">
              <span>キレてるね!</span>
            </div>
          </div>
        </div>
        <div class="micropost_timestamp">
          <span><%= time_ago_in_words(micropost.created_at) %>前</span>
        </div>
      </div>
      <% else %>
      <div class="garaly_img">
        <%= image_tag micropost.picture.url %>
      </div>
      <% end %>
    </a>
    <div class="micropost_reply">
      <%= form_with model: @reply, url: replies_path, local: true do |f| %>
        <%= hidden_field_tag :micropost_id, micropost.id %>
        <div class="reply_field">
          <%= f.text_area :content, id: "muscle_post_content", placeholder: "コメントする" %>
          <%= f.submit "送信", class: "btn reply_btn" %>
        </div>
      <% end %>
    </div>
  </article>
</li>

app/views/microposts/_new.html.erb
<div class="muscle_post_frame">
  <button type="button" id="muscle_post_close" class="close">&times;</button>
  <%= form_with model: @new_micropost, local: true do |f| %>
    <div class="muscle_post_field">
      <%= f.text_area :content, placeholder: "あなたのマッスルネタを共有しよう！", id: "muscle_post_content" %>
    </div>
    <div class="">
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', id: "muscle_post_picture" %>
      </span>
      <%= f.submit "投稿する", class: "btn btn-primary muscle_post_btn", disabled: false %>
    </div>
  <% end %>
</div>

app/views/microposts/show.html.erb
<div class="micropost">
  <div class="micropost_sticky">
    <div class="micropost_back_btn">
      <a href="<%= root_path %>">←</a>
    </div>
  </div>
</div>
<div class="micropost_detail">
  <article class="">
    <header>
      <div class="micropost_profile_img">
        <a href="<%= user_path(@micropost.user) %>"><%= image_tag @micropost.user.image_name.url %></a>
      </div>
      <div class="">
        <a href="<%= user_path(@micropost.user) %>"><%= @micropost.user.name %></a>
      </div>
    </header>
    <div class="micropost_main">
      <% if @micropost.picture? %>
      <div class="micropost_main_img">
        <%= image_tag @micropost.picture.url %>
      </div>
      <% end %>
      <div class="micropost_content">
        <span><%= @micropost.content %></span>
      </div>
      <div class="micropost_reaction">
        <div class="reply">
          <img src="/images/reply.svg" width="24" height="24" alt="">
        </div>
        <div class="remuscle">
          <img src="/images/remuscle.svg" width="24" height="24" alt="">
        </div>
        <div class="like">
          <img src="/images/like.svg" width="24" height="24" alt="">
          <div class="like_message">
            <span>キレてるね!</span>
          </div>
        </div>
        <% if current_user?(@micropost.user) %>
        <div class="delete">
          <%= link_to @micropost, method: :delete, data: { confirm: "削除しますか？" } do %>
            <img src="/images/delete.svg" width="24" height="24" alt="">
          <% end %>
        </div>
        <% end %>
      </div>

      <div class="micropost_timestamp">
        <span><%= @micropost.created_at.strftime("%Y-%m-%d %H:%M") %></span>
      </div>
    </div>

    <div class="micropost_reply">
      <%= form_with model: @reply, url: replies_path, local: true do |f| %>
        <%= hidden_field_tag :micropost_id, @micropost.id %>
        <div class="reply_field">
          <%= f.text_area :content, id: "muscle_post_content", placeholder: "コメントする" %>
          <%= f.submit "送信", class: "btn reply_btn" %>
        </div>
      <% end %>
    </div>
  </article>
</div>

<% if @replies.any? %>
<div class="micropost_replies">
  <ol>
    <%= render @replies %>
  </ol>
</div>
<% end %>