config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/prepare',   to: 'static_pages#prepare'
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/health_records',  to: 'health_records#new'
  get '/meal_records', to: 'meal_records#new'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers, :students, :header_records, :meal_records
    end
  end
  resources :microposts, only: [:show, :create, :destroy] do
    resources :reposts, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :deep_relationships, only: [:create, :destroy]
  resources :health_records, only: [:create, :destroy]
  resources :meal_records, only: [:edit, :create, :destroy]
  resources :replies, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar_fix">
  <div class="container header_flex">
    <div class="header_logo">
      <%= link_to "Muscle Platform", root_path, id: "logo", class: "notranslate" %>
    </div>
    <nav>
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li>
          <%= link_to root_url do %>
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
          <% end %>
        </li>
        <li>
          <%= link_to prepare_path(:title => 'メッセージ') do %>
          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
          <% end %>
        </li>
        <li>
          <%= link_to prepare_path(:title => '通知') do %>
          <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>
          <% end %>
        </li>
         <li>
           <%= link_to current_user, class:"nav_icon_bg" do %>
            <%= image_tag current_user.image_name.url, class: "nav_icon" %>
           <% end %>
         </li>
         <li class="new_post_bg dropdown">
           <a href="#" class="dropdown-toggle" id="new_post" data-toggle="dropdown">
             <span>+</span>
           </a>
           <ul class="dropdown-menu">
             <li><a id="muscle_post">投稿</a></li>
             <li><%= link_to "体重管理", health_records_path %></li>
             <li><%= link_to "食事管理", meal_records_path %></li>
            </ul>
         </li>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle setting" data-toggle="dropdown">
             ▼
           </a>
           <ul class="dropdown-menu">
             <li><%= link_to "設定", edit_user_path(current_user) %></li>
             <li><%= link_to "使い方", prepare_path(:title => '使い方') %></li>
             <li><%= link_to "ヘルプ", prepare_path(:title => 'ヘルプ') %></li>
             <li>
               <%= link_to "ログアウト", logout_path, method: :delete %>
             </li>
           </ul>
          </li>
       <% else %>
         <li><%= link_to "使い方", about_path %></li>
         <li><%= link_to "ヘルプ", help_path %></li>
         <% if current_page?(login_path) %>
         <li><%= link_to "新規登録", signup_path %></li>
         <% else %>
         <li><%= link_to "ログイン", login_path %></li>
         <% end %>
       <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="notranslate"><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class= <%= bg_style(@bg_url) %>>
      <%= render 'layouts/header' %>
      <div class="container main_contents">
        <%= yield %>
      </div>
      <%= render 'meal_records/edit' if logged_in? %>
      <%= render 'health_records/edit' if logged_in? %>
      <div id="mask"></div>
      <%= render 'microposts/new' if logged_in? %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> " id="flash">
          <div class="container">
            <%= message %>
          </div>
        </div>
        <div id="flash_filter">
        </div>
      <% end %>
    </div>
  </body>
</html>